CREATE TABLE airlines (
    IATA_CODE VARCHAR(5),
    AIRLINE VARCHAR(200),
    PRIMARY KEY(IATA_CODE)
);


CREATE TABLE airports (
    IATA_CODE VARCHAR(5),
    AIRPORT VARCHAR(200),
    CITY VARCHAR(200),
    STATE VARCHAR(200),
    COUNTRY VARCHAR(200),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    PRIMARY KEY(IATA_CODE)  
);


CREATE TABLE flights (
    YEAR INT,
    MONTH INT,
    DAY INT, 
    DAY_OF_WEEK INT,
    AIRLINE VARCHAR(5),
    FLIGHT_NUMBER VARCHAR(64),
    TAIL_NUMBER VARCHAR(64),
    ORIGINAL_AIRPORT VARCHAR(5),
    DESTINATION_AIRPORT VARCHAR(5),
    SCHEDULED_DEPARTURE TIME,
    WHEELS_OFF TIME,
    TAXI_OUT INT,
    DEPARTURE_TIME TIME,
    DEPARTURE_DELAY INT,
    SCHEDULED_TIME INT,
    AIR_TIME INT,
    TAXI_IN INT, 
    ELAPSED_TIME INT,
    DISTANCE INT,
    WHEELS_ON TIME, 
    SCHEDULED_ARRIVAL TIME, 
    ARRIVAL_TIME TIME, 
    ARRIVAL_DELAY INT,
    DIVERTED INT, 
    CANCELLED INT,
    CANCELLATION_REASON VARCHAR(10),
    AIR_SYSTEM_DELAY INT NULL,
    SECURITY_DELAY INT NULL,
    AIRLINE_DELAY INT NULL,
    LATE_AIRCRAFT_DELAY INT NULL,
    WEATHER_DELAY INT NULL,
    PRIMARY KEY(FLIGHT_NUMBER),
    FOREIGN KEY (AIRLINE) REFERENCES airlines(IATA_CODE),
    FOREIGN KEY (ORIGINAL_AIRPORT) REFERENCES airports(IATA_CODE),
    FOREIGN KEY (DESTINATION_AIRPORT) REFERENCES airports(IATA_CODE)
);